FROM php:8.2-fpm

WORKDIR /var/www/html

# Install dependensi yang diperlukan
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-install pdo_mysql zip mbstring exif pcntl bcmath \
    && pecl install redis \
    && docker-php-ext-enable redis

# Menginstall Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Expose port jika diperlukan (tidak diperlukan untuk PHP-FPM)
# EXPOSE 9000

# Perintah yang akan dijalankan saat container dijalankan
CMD ["php-fpm"]
