FROM nginx:latest

# Menyalin konfigurasi Nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/laravel.conf /etc/nginx/conf.d/default.conf

# Menyalin file konfigurasi PHP-FPM
COPY fastcgi-php.conf /etc/nginx/snippets/

# Menyalin konten web Laravel
COPY --from=laravel-app /var/www/html/public /var/www/html/public


# Expose port jika diperlukan
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
